import { existsSync } from 'fs';
import { writeTextFile, readTextFile, ensureDir } from '../util/io.js';
import { dirname } from 'path';
import { join } from 'path';
import type { ProjectContext } from './install.detect.js';
import type { ExtractedTokens } from './install.tokens.js';

const MARKER = '/* design-memory tokens */';

/**
 * Write design tokens into the project based on detected context.
 * Returns list of files created/modified.
 */
export async function writeTokensToProject(
  ctx: ProjectContext,
  tokens: ExtractedTokens,
): Promise<string[]> {
  const written: string[] = [];

  // 1. Write CSS variables to globals.css
  if (tokens.cssVariablesBlock) {
    await appendToGlobals(ctx.globalsPath, tokens.cssVariablesBlock);
    written.push(ctx.globalsPath);
  }

  // 2. Write Tailwind extend to tailwind.config
  if (ctx.hasTailwind && ctx.tailwindConfigPath && tokens.tailwindExtendBlock) {
    await appendTailwindExtend(ctx.tailwindConfigPath, tokens.tailwindExtendBlock);
    written.push(ctx.tailwindConfigPath);
  }

  // 3. Write tokens.ts
  if (tokens.cssVariablesBlock) {
    const tokensPath = join(ctx.tokensDir, 'design-tokens.ts');
    await writeTokensFile(tokensPath, tokens.cssVariablesBlock);
    written.push(tokensPath);
  }

  return written;
}

async function appendToGlobals(path: string, cssBlock: string): Promise<void> {
  await ensureDir(dirname(path));

  let content = '';
  if (existsSync(path)) {
    content = await readTextFile(path);
    if (content.includes(MARKER)) return; // already installed
  }

  const section = `\n${MARKER}\n${cssBlock}\n`;
  await writeTextFile(path, content + section);
}

async function appendTailwindExtend(configPath: string, extendBlock: string): Promise<void> {
  if (!existsSync(configPath)) return;

  const content = await readTextFile(configPath);
  if (content.includes(MARKER)) return; // already installed

  // Add the extend block as a comment reference at the end of the file
  const comment = `\n/*\n${MARKER}\nMerge this into your theme.extend:\n\n${extendBlock}\n*/\n`;
  await writeTextFile(configPath, content + comment);
}

async function writeTokensFile(path: string, cssBlock: string): Promise<void> {
  await ensureDir(dirname(path));

  if (existsSync(path)) {
    const content = await readTextFile(path);
    if (content.includes(MARKER)) return; // already installed
  }

  // Parse CSS variables from the block into a TS object
  const vars: Record<string, string> = {};
  const regex = /--([\w-]+)\s*:\s*([^;]+);/g;
  let match: RegExpExecArray | null;

  while ((match = regex.exec(cssBlock)) !== null) {
    const name = match[1]!.replace(/-/g, '_').replace(/__/g, '_');
    vars[name] = match[2]!.trim();
  }

  const lines: string[] = [
    `// ${MARKER}`,
    `// Auto-generated by design-memory install. Do not edit manually.`,
    '',
    `export const designTokens = {`,
  ];

  for (const [name, value] of Object.entries(vars)) {
    lines.push(`  ${name}: '${value}',`);
  }

  lines.push('} as const;');
  lines.push('');

  await writeTextFile(path, lines.join('\n'));
}
